#########################################
#          Heater automations           #
#########################################


- alias: Update real heater with combined sensor status
  trigger:
    platform: time
    minutes: '/5'
    seconds: 00
  action:
    service_template: >
      {% if is_state('binary_sensor.heater_combined', 'on') %}
        switch.turn_on
      {% elif is_state('binary_sensor.heater_combined', 'off') %}
        switch.turn_off
      {% endif %}
    entity_id: switch.caldera_1_3

